Fix activity names
temporalio/temporal-aws-sdk pull request #12
Opened 2020-10-04 20:12 UTC by sagikazarmark

2020-10-05 21:52 UTC, mfateev approved these changes

2020-10-05 21:54 UTC, mfateev requested changes
What about activity registration?
It is defined in activities_global.tmpl

2020-10-05 21:56 UTC, sagikazarmark commented
I actually did that in a previous PR, but forgot to update the clients. This PR fixes that mistake.

2020-10-06 01:59 UTC, mfateev approved these changes

2020-10-06 01:59 UTC, merged